CREATE TABLE IF NOT EXISTS account (
	id INTEGER NOT NULL AUTO_INCREMENT,
	parentid INTEGER NOT NULL,
	token VARCHAR(255),
	userid BIGINT,
	accesstoken VARCHAR(255),
	accesstokensecret VARCHAR(255),
	expiration DATETIME NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	INDEX(parentid)
);

CREATE TABLE IF NOT EXISTS query (
	id INTEGER NOT NULL AUTO_INCREMENT,
	accountid INTEGER NOT NULL,
	query LONGTEXT NOT NULL,
	failcount INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(id),
	INDEX(failcount),
	FOREIGN KEY (accountid) REFERENCES account(id)
);